In [1]:
import numpy as np

In [20]:
notre_tableau = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [18]:
notre_tableau

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [4]:
mon_array_bidimentionnel = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
mon_array_bidimentionnel

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### (view) un sous-tableau : modif de sous tableau => modif de tableau d'origine  

In [6]:
sous_tableau = notre_tableau[0:5]

In [7]:
sous_tableau

array([1, 2, 3, 4, 5])

In [8]:
sous_tableau[0] = 10
sous_tableau

array([10,  2,  3,  4,  5])

In [21]:
notre_tableau

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#copy et view -> (sous_tableau) d'un tableau

In [23]:
sous_tableau1 = notre_tableau[0:5].copy()
sous_tableau1[0]=99

In [24]:
sous_tableau1

array([99,  2,  3,  4,  5])

In [25]:
notre_tableau

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
mon_array_bidimentionnel

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
mon_array_bidimentionnel[1,2]

6

In [31]:
mon_array_bidimentionnel[1,-1]

6

In [32]:
mon_array_bidimentionnel[:,0]

array([1, 4, 7])

In [36]:
liste1 = list(mon_array_bidimentionnel[0,:])
liste1

[1, 2, 3]

In [37]:
liste1[1:]

[2, 3]

In [42]:
mon_array_bidimentionnel[:,0:3:2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [43]:
mon_array_bidimentionnel[:,1:-1]

array([[2],
       [5],
       [8]])

In [49]:
mon_array_bidimentionnel[2,1:-1]

array([8])

In [55]:
#Tableau bidimentionnel de dimension 6 lignes et 4 colonnes (et ses valeurs vont de 0 a 100)

In [76]:
array = np.random.randint(100,size=(6,4))
array

array([[29, 59, 70, 25],
       [87, 49, 20, 59],
       [57, 65, 77, 33],
       [62, 95, 36, 48],
       [10, 84, 56, 65],
       [50, 30, 56, 85]])

In [77]:
array.min()

10

In [78]:
array.max()

95

In [79]:
array.mean()

54.458333333333336

### Transformation de liste en array 

In [63]:
liste2 = [2,8,9,10,11,15,25]
liste2_array = np.array(liste2)
liste2_array[liste2_array>10]

array([11, 15, 25])

### dimension de mon tableau

In [80]:
array.ndim

2

In [81]:
array.shape

(6, 4)

In [82]:
array.dtype

dtype('int32')

In [83]:
array.size

24

In [90]:
array[array<=50]

array([29, 25, 49, 20, 33, 36, 48, 10, 50, 30])

In [92]:
array[(array>50) & (array<=70)]

array([59, 70, 59, 57, 65, 62, 56, 65, 56])

In [93]:
array[(array>50) | (array<=40)]

array([29, 59, 70, 25, 87, 20, 59, 57, 65, 77, 33, 62, 95, 36, 10, 84, 56,
       65, 30, 56, 85])

In [97]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[2,5,6],[9,10,11],[5,6,9]])

In [98]:
#concatenation de deux tableau
np.concatenate([array1,array2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  5,  6],
       [ 9, 10, 11],
       [ 5,  6,  9]])

In [104]:
array3 = np.array([[4,10,13],[8,5,41]])

### Contactenation de deux arrays 

In [105]:
np.concatenate([array1, array2, array3])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  5,  6],
       [ 9, 10, 11],
       [ 5,  6,  9],
       [ 4, 10, 13],
       [ 8,  5, 41]])

In [106]:
array1 = np.array([15,16,47])

In [107]:
array1

array([15, 16, 47])

In [110]:
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### np.concatenate: prend deux arrays avec les memes dimensions 

In [111]:
np.concatenate([array1,array2])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

### np.vstack: empilation verticale ajout d'une valeur par colonne (donc ajout d'une ligne) 

In [112]:
np.vstack([array1,array2])

array([[15, 16, 47],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

### np.hstack : Empilation horizontale  Ajout d'une colonne (ajout d'une valeur par ligne)

In [118]:
#tableau bidimentionnel contennant une liste de liste
array1 = np.array([[15],[16],[47]])
array1

array([[15],
       [16],
       [47]])

In [117]:
np.hstack([array1,array2])

array([[15,  1,  2,  3],
       [16,  4,  5,  6],
       [47,  7,  8,  9]])

### split de tableau unidimentionnel 'vecteur'  (casser le tableau en morceau +ieurs tableau) 

In [119]:
array = np.array([15,16,17,12,49,52,12,14,36])

In [121]:
len(array)

9

###  np.split(array,[2,6])
###### point de cassur index2 et index6 => [15,16,17,12,49,52,12,14,36] sample : index 2 = 17 donc a partir de 17  on casse
deux point de cassur ça veut dire 3 tableaux

In [122]:
np.split(array,[2,6])

[array([15, 16]), array([17, 12, 49, 52]), array([12, 14, 36])]

In [123]:
array1, array2, array3 = np.split(array,[2,6])

In [126]:
print(array1,array2,array3)

[15 16] [17 12 49 52] [12 14 36]


In [323]:
#vsplit : np(split par ligne) hsplit(np split par colonne)

### split de tableau mutidimentionnel  (casser le tableau en morceau +ieurs tableau soit vertical soit horizontale)  

In [317]:
array2 = np.array([[2,5,6],[9,10,11],[5,6,9]])

In [318]:
print(array2)

[[ 2  5  6]
 [ 9 10 11]
 [ 5  6  9]]


In [319]:
array1,array1_10 = np.vsplit(array2,[2])

In [320]:
print(array1)
print()
print(array1_10)

[[ 2  5  6]
 [ 9 10 11]]

[[5 6 9]]


In [324]:
array2_1,array2_10 = np.hsplit(array2,[2])

In [325]:
print(array2_1)
print()
print(array2_10)

[[ 2  5]
 [ 9 10]
 [ 5  6]]

[[ 6]
 [11]
 [ 9]]


### calcul sur les tableaux

In [150]:
array_calcul = np.random.randint(350,size=(10,9))

In [151]:
array_calcul

array([[104, 295, 250,  73, 182, 335,  27,   7, 213],
       [ 79, 245,  15, 343,  64,  80, 266, 105, 149],
       [189,  40, 162,  21, 236,  42, 184,  22,  87],
       [ 72, 268,   3, 107, 308, 311,   6, 188,  44],
       [266, 314,  21,  81, 299, 286, 186,   5, 124],
       [106,  94, 110, 178,  11,  70,  55, 152, 226],
       [290, 233,  63,  56,  39, 320, 134, 303, 116],
       [ 80, 321, 121,  66, 248, 198,  60, 144, 247],
       [ 87,  66, 147, 251, 279,  67, 186,  65,   2],
       [  1,  47,  65, 311,  52,  17, 337, 321,  75]])

In [153]:
array_calcul+2

array([[106, 297, 252,  75, 184, 337,  29,   9, 215],
       [ 81, 247,  17, 345,  66,  82, 268, 107, 151],
       [191,  42, 164,  23, 238,  44, 186,  24,  89],
       [ 74, 270,   5, 109, 310, 313,   8, 190,  46],
       [268, 316,  23,  83, 301, 288, 188,   7, 126],
       [108,  96, 112, 180,  13,  72,  57, 154, 228],
       [292, 235,  65,  58,  41, 322, 136, 305, 118],
       [ 82, 323, 123,  68, 250, 200,  62, 146, 249],
       [ 89,  68, 149, 253, 281,  69, 188,  67,   4],
       [  3,  49,  67, 313,  54,  19, 339, 323,  77]])

In [154]:
array_calcul-2

array([[102, 293, 248,  71, 180, 333,  25,   5, 211],
       [ 77, 243,  13, 341,  62,  78, 264, 103, 147],
       [187,  38, 160,  19, 234,  40, 182,  20,  85],
       [ 70, 266,   1, 105, 306, 309,   4, 186,  42],
       [264, 312,  19,  79, 297, 284, 184,   3, 122],
       [104,  92, 108, 176,   9,  68,  53, 150, 224],
       [288, 231,  61,  54,  37, 318, 132, 301, 114],
       [ 78, 319, 119,  64, 246, 196,  58, 142, 245],
       [ 85,  64, 145, 249, 277,  65, 184,  63,   0],
       [ -1,  45,  63, 309,  50,  15, 335, 319,  73]])

In [158]:
array_calcul[:,0]*10

array([1040,  790, 1890,  720, 2660, 1060, 2900,  800,  870,   10])

In [160]:
np.add(array_calcul,2)

array([[106, 297, 252,  75, 184, 337,  29,   9, 215],
       [ 81, 247,  17, 345,  66,  82, 268, 107, 151],
       [191,  42, 164,  23, 238,  44, 186,  24,  89],
       [ 74, 270,   5, 109, 310, 313,   8, 190,  46],
       [268, 316,  23,  83, 301, 288, 188,   7, 126],
       [108,  96, 112, 180,  13,  72,  57, 154, 228],
       [292, 235,  65,  58,  41, 322, 136, 305, 118],
       [ 82, 323, 123,  68, 250, 200,  62, 146, 249],
       [ 89,  68, 149, 253, 281,  69, 188,  67,   4],
       [  3,  49,  67, 313,  54,  19, 339, 323,  77]])

In [161]:
np.subtract(array_calcul,7)

array([[ 97, 288, 243,  66, 175, 328,  20,   0, 206],
       [ 72, 238,   8, 336,  57,  73, 259,  98, 142],
       [182,  33, 155,  14, 229,  35, 177,  15,  80],
       [ 65, 261,  -4, 100, 301, 304,  -1, 181,  37],
       [259, 307,  14,  74, 292, 279, 179,  -2, 117],
       [ 99,  87, 103, 171,   4,  63,  48, 145, 219],
       [283, 226,  56,  49,  32, 313, 127, 296, 109],
       [ 73, 314, 114,  59, 241, 191,  53, 137, 240],
       [ 80,  59, 140, 244, 272,  60, 179,  58,  -5],
       [ -6,  40,  58, 304,  45,  10, 330, 314,  68]])

In [162]:
np.multiply(array_calcul,2)

array([[208, 590, 500, 146, 364, 670,  54,  14, 426],
       [158, 490,  30, 686, 128, 160, 532, 210, 298],
       [378,  80, 324,  42, 472,  84, 368,  44, 174],
       [144, 536,   6, 214, 616, 622,  12, 376,  88],
       [532, 628,  42, 162, 598, 572, 372,  10, 248],
       [212, 188, 220, 356,  22, 140, 110, 304, 452],
       [580, 466, 126, 112,  78, 640, 268, 606, 232],
       [160, 642, 242, 132, 496, 396, 120, 288, 494],
       [174, 132, 294, 502, 558, 134, 372, 130,   4],
       [  2,  94, 130, 622, 104,  34, 674, 642, 150]])

In [165]:
np.divide(array_calcul, 50)

array([[2.08, 5.9 , 5.  , 1.46, 3.64, 6.7 , 0.54, 0.14, 4.26],
       [1.58, 4.9 , 0.3 , 6.86, 1.28, 1.6 , 5.32, 2.1 , 2.98],
       [3.78, 0.8 , 3.24, 0.42, 4.72, 0.84, 3.68, 0.44, 1.74],
       [1.44, 5.36, 0.06, 2.14, 6.16, 6.22, 0.12, 3.76, 0.88],
       [5.32, 6.28, 0.42, 1.62, 5.98, 5.72, 3.72, 0.1 , 2.48],
       [2.12, 1.88, 2.2 , 3.56, 0.22, 1.4 , 1.1 , 3.04, 4.52],
       [5.8 , 4.66, 1.26, 1.12, 0.78, 6.4 , 2.68, 6.06, 2.32],
       [1.6 , 6.42, 2.42, 1.32, 4.96, 3.96, 1.2 , 2.88, 4.94],
       [1.74, 1.32, 2.94, 5.02, 5.58, 1.34, 3.72, 1.3 , 0.04],
       [0.02, 0.94, 1.3 , 6.22, 1.04, 0.34, 6.74, 6.42, 1.5 ]])

In [167]:
np.mean(array_calcul)
print("la moyenne de tableau %.2f" %(np.mean(array_calcul)))

la moyenne de tableau 145.79


In [168]:
array_calcul.mean()

145.7888888888889

In [169]:
array_calcul.min()

1

In [170]:
array_calcul.max()

343

### moyenne par colonne

In [172]:
np.mean(array_calcul,axis=0)

array([127.4, 192.3,  95.7, 148.7, 171.8, 172.6, 144.1, 131.2, 128.3])

### moyenne par ligne 

In [173]:
np.mean(array_calcul,axis=1)

array([165.11111111, 149.55555556, 109.22222222, 145.22222222,
       175.77777778, 111.33333333, 172.66666667, 165.        ,
       127.77777778, 136.22222222])

## importer un fichier csv avec pandas

In [338]:
import pandas as pd
data = pd.read_csv('Houses.csv')

## importer un fichier csv avec numpy

In [339]:
data_houses = np.genfromtxt('Houses.csv', delimiter=",", dtype = int)

In [340]:
data_houses

array([[212000,   4148,  25264],
       [230000,   2501,  11891],
       [339000,   4374,  25351],
       [289000,   2398,  22215],
       [160000,   2536,   9234],
       [ 85000,   2368,  13329],
       [ 85000,   1264,   8407],
       [145000,   1572,  12588],
       [164000,   2375,  16204],
       [123500,   1161,   9626],
       [180000,   1542,   8755],
       [159500,   1464,  14636],
       [156000,   2240,  21780],
       [146500,   1269,  11250],
       [101500,    924,   7361],
       [109800,    768,  10497],
       [182000,   1320,  15768],
       [110000,   1845,  12153],
       [125000,   1274,  13634],
       [ 80000,   1905,  10890]])

In [186]:
data_houses.ndim
data_houses.shape

(20, 3)

In [275]:
data_houses[:,0] = data_houses[:,0]*(0.86)

In [276]:
data_houses[:,1:] = data_houses[:,1:]*(0.09)

In [277]:
data_houses

array([[182320,    373,   2273],
       [197800,    225,   1070],
       [291540,    393,   2281],
       [248540,    215,   1999],
       [137600,    228,    831],
       [ 73100,    213,   1199],
       [ 73100,    113,    756],
       [124700,    141,   1132],
       [141040,    213,   1458],
       [106210,    104,    866],
       [154800,    138,    787],
       [137170,    131,   1317],
       [134160,    201,   1960],
       [125990,    114,   1012],
       [ 87290,     83,    662],
       [ 94428,     69,    944],
       [156520,    118,   1419],
       [ 94600,    166,   1093],
       [107500,    114,   1227],
       [ 68800,    171,    980]])

In [297]:
len(data_houses[data_houses[:,2]>1000])

13

In [298]:
print("nombre de maison qui possede un terrain >1000 m2 => ", len(data_houses[data_houses[:,2]>1000]), " maisons")

nombre de maison qui possede un terrain >1000 m2 =>  13  maisons


In [282]:
print("La somme des prix de vente", np.sum(data_houses[:,0:1]))

La somme des prix de vente 2737208


In [231]:
data_houses

array([[212000,   4148,  25264],
       [230000,   2501,  11891],
       [339000,   4374,  25351],
       [289000,   2398,  22215],
       [160000,   2536,   9234],
       [ 85000,   2368,  13329],
       [ 85000,   1264,   8407],
       [145000,   1572,  12588],
       [164000,   2375,  16204],
       [123500,   1161,   9626],
       [180000,   1542,   8755],
       [159500,   1464,  14636],
       [156000,   2240,  21780],
       [146500,   1269,  11250],
       [101500,    924,   7361],
       [109800,    768,  10497],
       [182000,   1320,  15768],
       [110000,   1845,  12153],
       [125000,   1274,  13634],
       [ 80000,   1905,  10890]])

In [301]:
max_prix = np.max(data_houses[:,0])
max_prix

291540

In [308]:
data_houses[data_houses[:,0] == max_prix]

array([[291540,    393,   2281]])

In [240]:
data_houses

array([[212000,   4148,  25264],
       [230000,   2501,  11891],
       [339000,   4374,  25351],
       [289000,   2398,  22215],
       [160000,   2536,   9234],
       [ 85000,   2368,  13329],
       [ 85000,   1264,   8407],
       [145000,   1572,  12588],
       [164000,   2375,  16204],
       [123500,   1161,   9626],
       [180000,   1542,   8755],
       [159500,   1464,  14636],
       [156000,   2240,  21780],
       [146500,   1269,  11250],
       [101500,    924,   7361],
       [109800,    768,  10497],
       [182000,   1320,  15768],
       [110000,   1845,  12153],
       [125000,   1274,  13634],
       [ 80000,   1905,  10890]])

In [334]:
prix, taille_maison, taille_terrain = np.hsplit(data_houses,3)

In [335]:
print(prix,taille_maison,taille_maison)

[[182320]
 [197800]
 [291540]
 [248540]
 [137600]
 [ 73100]
 [ 73100]
 [124700]
 [141040]
 [106210]
 [154800]
 [137170]
 [134160]
 [125990]
 [ 87290]
 [ 94428]
 [156520]
 [ 94600]
 [107500]
 [ 68800]] [[373]
 [225]
 [393]
 [215]
 [228]
 [213]
 [113]
 [141]
 [213]
 [104]
 [138]
 [131]
 [201]
 [114]
 [ 83]
 [ 69]
 [118]
 [166]
 [114]
 [171]] [[373]
 [225]
 [393]
 [215]
 [228]
 [213]
 [113]
 [141]
 [213]
 [104]
 [138]
 [131]
 [201]
 [114]
 [ 83]
 [ 69]
 [118]
 [166]
 [114]
 [171]]


In [337]:
house_original = np.concatenate([prix,taille_maison,taille_terrain], axis=1)
house_original

array([[182320,    373,   2273],
       [197800,    225,   1070],
       [291540,    393,   2281],
       [248540,    215,   1999],
       [137600,    228,    831],
       [ 73100,    213,   1199],
       [ 73100,    113,    756],
       [124700,    141,   1132],
       [141040,    213,   1458],
       [106210,    104,    866],
       [154800,    138,    787],
       [137170,    131,   1317],
       [134160,    201,   1960],
       [125990,    114,   1012],
       [ 87290,     83,    662],
       [ 94428,     69,    944],
       [156520,    118,   1419],
       [ 94600,    166,   1093],
       [107500,    114,   1227],
       [ 68800,    171,    980]])

In [331]:
np.hstack([prix,taille_maison,taille_terrain])

array([[182320,    373,   2273],
       [197800,    225,   1070],
       [291540,    393,   2281],
       [248540,    215,   1999],
       [137600,    228,    831],
       [ 73100,    213,   1199],
       [ 73100,    113,    756],
       [124700,    141,   1132],
       [141040,    213,   1458],
       [106210,    104,    866],
       [154800,    138,    787],
       [137170,    131,   1317],
       [134160,    201,   1960],
       [125990,    114,   1012],
       [ 87290,     83,    662],
       [ 94428,     69,    944],
       [156520,    118,   1419],
       [ 94600,    166,   1093],
       [107500,    114,   1227],
       [ 68800,    171,    980]])